on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: ljcmps01/avrgcc-3.7.0:latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - run: tree
    - run: TOOLS_PATH="/home/ubuntu/dev/tools" make
    - run: make cppcheck
